services:
  note-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/app
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"
    stdin_open: true
    tty: true
